/**
 * Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
 */

console.log('print subsequence', subsequence('abc'));

function subsequence(str){
    let curr = "";
    let index = 0;
    let ans = [];
    solve(str, index, curr, ans)
    return ans;
}   

function solve(str, index, curr, ans){
    if(index >= str.length){
        ans.push(curr)
        console.log(curr)
        return;
    }

    // exclude 
    solve(str, index+1, curr, ans);

    // include
    let temp = str[index];
    curr += temp;
    solve(str, index+1, curr, ans);
}